name: Deploy Backend to Cloud Functions

on:
  push:
    branches:
      - develop

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/694385104566/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gemini-cli-runner@pm-bot-prod.iam.gserviceaccount.com'

      - name: 'Deploy to Cloud Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'your-function-name'
          runtime: 'nodejs20'
          entry_point: 'yourEntryPoint'
          source_dir: './functions' # Assuming your functions are in a 'functions' directory
