name: Deploy Backend to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
        working-directory: ./functions
      - name: Run Tests
        run: npm test
        working-directory: ./functions

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/694385104566/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gemini-cli-runner@pm-bot-prod.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy to Cloud Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'pm-bot-conversational-engine'
          runtime: 'nodejs20'
          entry_point: 'conversationalHandler'
          source_dir: './functions'
          region: 'us-central1'
          service_account_email: 'pm-bot-prod@appspot.gserviceaccount.com'
